services:
  db:
    image: mysql:latest
    container_name: mysql_monitor
    restart: always
    environment:
      # Need change here
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoringdb
      MYSQL_USER: monitoring
      MYSQL_PASSWORD: monitoring
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - my_network

volumes:
  db_data:
    driver: local

networks:
  my_network:
    driver: bridge